### ISSUE TITLE
AttributeError: module 'pymesh' has no attribute 'snap_rounding'

### ISSUE THREAD

**Issue by chwongAI** [syinari0123/tridepth#2]
Your work is very interesting, and I was trying to run it however, I ran into the issue:

AttributeError: module 'pymesh' has no attribute 'snap_rounding'

I wasn't able to "pip install PyMesh==0.2.1" (as it was not found), so I ended up download the .whl from https://github.com/PyMesh/PyMesh/releases and pip installed the .whl file.

I did check my site-packages' pymesh, and confirm that I snap_rounding doesn't exist. I can find snap_rounding2 from this link tho: https://github.com/PyMesh/PyMesh/blob/ddbcff950954e59deb0f2284b3e529134a6e7cf0/tools/CGAL/SnapRounding2.cpp

It would be great if you could help look into this.

**Comment by syinari0123** [comment]
Thank you for reporting!
I briefly checked that PyMesh==0.2.1 doesn't currently exist in pip distribution, and 'snap_rounding' has already removed in newest pymesh.
So my code doesn't seem to work currently... :(
OK, I'll find a way to avoid this error! Please wait for a while.
