### ISSUE TITLE
Pretrained weights not available

### ISSUE THREAD

**Issue by NoordGuy** [syinari0123/tridepth#7]
Dear Masaya Kaneko,

thank you for bringing this project to github. I tried to download the pretrained weights to test the model, but the uri in /pretrained is no longer available:

`Location: /s/raw/oos76qomuvddu21/weight_upconv.pth [following]
----  https://www.dropbox.com/s/raw/oos76qomuvddu21/weight_upconv.pth
Reusing existing connection to [www.dropbox.com]:443.
HTTP request sent, awaiting response... 400 Bad Request`

Could you provide a new link to the weights?

**Comment by syinari0123** [comment]
Thank you for reporting! I fixed the missing download link of the pretrained model in https://github.com/syinari0123/tridepth/commit/5e7e90b537b82e731bb6beac1c8c93fc9187fee0.
